# -*- coding: utf-8 -*-
"""DIO Analise de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBcxul2CE72JocaJtTZsOQvmuFZC0Rqg
"""

import pandas as pd

df = pd.read_csv('SDW2023.csv')
user_ids = df['UserID'].tolist()
print(user_ids)
#

import requests
import json
users_api = 'https://dummyjson.com/'
def get_user(id):
  response = requests.get(f'{users_api}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id)) is not None]
print(json.dumps(users, indent=2))
#

!pip install -U google-genai

from google import genai
from google.colab import userdata

# Retrieve the API key securely from Colab's Secrets Manager
client = genai.Client(api_key=userdata.get('GEMINI_API_KEY'))

interaction = client.interactions.create(
    model="gemini-3.6-flash",
    input="Explique a IA em 2 paragrafo"
)
print(interaction.output_text)

import google.generativeai as genai
from google.colab import userdata

# Configure a chave da API do Gemini
genai.configure(api_key=userdata.get('GEMINI_API_KEY'))

# Inicialize o modelo Gemini
model = genai.GenerativeModel('gemini-1.5-flash') # Usando 'gemini-1.5-flash' como um modelo rápido e eficaz

def generate_investment_message(user_first_name):
  prompt_parts = [
    "Você é um especialista em marketing bancário. Crie uma mensagem para ",
    f"{user_first_name} sobre a importância dos investimentos (máximo de 100 caracteres)"
  ]
  try:
    response = model.generate_content(prompt_parts)
    return response.text.strip()
  except Exception as e:
    return f"Erro ao gerar mensagem para {user_first_name}: {e}"

# Gerar e imprimir mensagens para cada usuário
print("Gerando mensagens personalizadas para cada usuário:")
for user in users:
  message = generate_investment_message(user['firstName'])
  print(f"Mensagem para {user['firstName']}: {message}")